# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodeBlue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeBlue
  pod 'Alamofire'
  pod 'Firebase/Messaging'
end

target 'CodeBlue WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeBlue WatchKit App

end

target 'CodeBlue WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodeBlue WatchKit Extension
  pod 'Alamofire'
end
